services:
  pg:
    image: postgres:15.6
    container_name: db
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neptune_db
      POSTGRES_USER: neptune
      POSTGRES_PASSWORD: neptune
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data: