include:
  - ../compose.yml

services:
  api:
    build: .
    container_name: gateway
    env_file:
      - ../.env
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    environment:
      GATEWAY_PORT: ${GATEWAY_PORT}
      GATEWAY_ORDER_ROUTE: ${GATEWAY_ORDER_ROUTE}
      GATEWAY_INVENTORY_ROUTE: ${GATEWAY_INVENTORY_ROUTE}

networks:
  api-network:
    name: api-network