DROP TABLE product IF EXISTS;

CREATE TABLE product
(
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) UNIQUE,
    qty        SMALLINT DEFAULT 0
);
CREATE INDEX IX_product_name ON product (name);