DROP TABLE IF EXISTS inventory;

CREATE TABLE inventory
(
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         UUID UNIQUE,
    name         VARCHAR(50) UNIQUE,
    qty          SMALLINT DEFAULT 0 CHECK (qty > 0)
);
CREATE INDEX IX_inventory_name ON inventory (uuid);
CREATE INDEX IX_inventory_uuid ON inventory (name);