server:
  port: ${INVENTORY_PORT:1997}
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param

logging:
  level:
    org:
      springframework:
        jdbc: trace

spring:
  application:
    name: inventory
  threads:
    virtual:
      enabled: true
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      mode: always
  profiles:
    active: ${PROFILE:e2e}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/neptune_db?sslmode=disable}
    username: ${DB_USERNAME:neptune}
    password: ${DB_PASSWORD:neptune}
    driver-class-name: org.postgresql.Driver

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9090}

route:
  prefix: api/v1/