logging:
  level:
    org:
      springframework=INFO: INFO

spring:
  application:
    name: inventory
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
  profiles:
    active: ${PROFILE:default}
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:postegre://localhost:3306/inventory_db}
    username: ${DB_USERNAME:inventory}
    password: ${DB_PASSWORD:inventory}

route:
  prefix: api/v1/