server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      routes:
        - id: order-route
          uri: ${ORDER_ROUTE:http://localhost:1998}
          predicates:
            - Path=/api/v1/order/**
#          filters:
#            - PrefixPath=/api/v1
        - id: INVENTORY-SERVICE
          uri: ${ORDER_ROUTE:http://localhost:1997}
          predicates:
            - Path=/api/v1/inventory/**
#          filters:
#            - PrefixPath=/api/v1