server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        wiretap: true
      routes:
        - id: order-route
          uri: ${GATEWAY_ORDER_ROUTE:http://localhost:1998}
          predicates:
            - Path=/api/v1/order/**
#          filters:
#            - PrefixPath=/api/v1
        - id: inventory-route
          uri: ${GATEWAY_INVENTORY_ROUTE:http://localhost:1997}
          predicates:
            - Path=/api/v1/inventory/**
#          filters:
#            - PrefixPath=/api/v1