services:
  database:
    image: postgres:15.6
    container_name: database
    env_file:
      - ../.env
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_HOST_PORT}:5432
    networks:
      - db-network
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  db-network:
    name: db-network

volumes:
  database-data: