name: Build & Test
on:
  push:
    branches:
      - backend
  pull_request:
    branches:
      - master
      - backend

jobs:
  individual-test:
    name: Test order and inventory modules separately
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Docker run
        run: |
          docker run --name pg \
          -p 5432:5432 \
          --expose 5432 \
          -e POSTGRES_DB=neptune_db \
          -e POSTGRES_USER=neptune \
          -e POSTGRES_PASSWORD=neptune \
          -d postgres:15.6

      - name: inventory tests
        run: |
          cd inventory/
          mvn clean test

      - name: order tests
        run: |
          cd order/
          mvn clean test

      - name: compose down
        run: docker stop pg

  e2e-test:
    name: e2e test
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: create .env
        run: |
          touch .env
          echo DB_NAME=neptune_db >> .env
          echo DB_HOST_PORT=5431 >> .env
          echo DB_URL='jdbc:postgresql://database:5432/neptune_db?sslmode=disable' >> .env
          echo DB_USERNAME=neptune >> .env
          echo DB_PASSWORD=neptune >> .env
          echo GATEWAY_PORT=4000 >> .env
          echo GATEWAY_ORDER_ROUTE=http://order:4002 >> .env
          echo GATEWAY_INVENTORY_ROUTE=http://inventory:4003 >> .env
          echo ORDER_PORT=4002 >> .env
          echo ORDER_PROFILE=default >> .env
          echo INVENTORY_CLIENT_ADDRESS=static://inventory:4005 >> .env
          echo INVENTORY_PORT=4003 >> .env
          echo INVENTORY_PROFILE=e2e >> .env
          echo INVENTORY_GRPC_SERVER_PORT=4005 >> .env

      - name: compose up
        run: docker compose -f compose-gateway.yml up -d

      - name: containers states
        run: docker ps

      - name: e2e test
        run: |
          cd e2e/
          javac main.java
          java main.java 4000

      - name: compose down
        run: docker compose down -v