name: Test & Build
on:
  push:
    branches:
      - backend
#      - '**'
  pull_request:
    branches:
      - master
      - backend

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Docker run
        run: |
          docker run --name pg \
          -p 5432:5432 \
          --expose 5432 \
          -e POSTGRES_DB=neptune_db \
          -e POSTGRES_USER=neptune \
          -e POSTGRES_PASSWORD=neptune \
          -d postgres:15.6

      - name: Inventory tests
        run: |
          cd inventory/
          mvn clean test

      - name: Order tests
        run: |
          cd order/
          mvn clean test

      - name: Docker stop
        run: docker stop pg

      - name: Compose up
        run: docker compose -f compose-ci.yml up -d

      - name: Create .env
        run: echo -e "DB_NAME=neptune_db\nDB_PORT=5432\nDB_URL='jdbc:postgresql://db:5432/neptune_db?sslmode=disable'\nDB_USERNAME=neptune\nDB_PASSWORD=neptune\n\n# gateway\nGATEWAY_PORT=8080\nGATEWAY_ORDER_ROUTE=http://order:1998\nGATEWAY_INVENTORY_ROUTE=http://inventory:1997\n\n# order\nORDER_PORT=1998\nORDER_PROFILE=default\nGRPC_CLIENT_ADDRESS=static://inventory:9090\n#GRPC_CLIENT_ADDRESS=static://127.0.0.1:9090\n\n# inventory\nINVENTORY_PORT=1997\nINVENTORY_PROFILE=e2e\nGRPC_SERVER_PORT=9090" > .env

      - name: e2e test
        run: |
          javac main.java
          java main.java 8080

      - name: Compose down
        run: docker compose down -v