name: Test & Build
on:
  push:
    branches:
      - backend
#      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: Docker run
        run: |
          docker run --name pg \
          -p 5432:5432 \
          --expose 5432 \
          -e POSTGRES_DB=neptune_db \
          -e POSTGRES_USER=neptune \
          -e POSTGRES_PASSWORD=neptune \
          -d postgres:15.6

      - name: Inventory tests
        run: |
          cd inventory/
          mvn clean test

      - name: Order tests
        run: |
          cd order/
          mvn clean test

      - name: Docker stop
        run: docker stop pg

      - name: Compose up
        run: docker compose up -d

      - name: e2e test
        run: |
          javac main.java
          java main.java 8080

      - name: Compose down
        run: docker compose down -v