name: Test & Build
on:
  push:
    branches:
      - backend
  pull_request:
    branches:
      - master
      - backend

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up JDK Temurin
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'

      - name: create .env
        run: |
          touch .env
          echo DB_NAME=neptune_db\n >> .env
          echo DB_HOST_PORT=5432\n >> .env
          echo DB_URL='jdbc:postgresql://database:5432/neptune_db?sslmode=disable'\n >> .env
          echo DB_USERNAME=neptune\n >> .env
          echo DB_PASSWORD=neptune\n >> .env
          echo GATEWAY_PORT=8080\n >> .env
          echo GATEWAY_ORDER_ROUTE=http://order:1998\n >> .env
          echo GATEWAY_INVENTORY_ROUTE=http://inventory:1997\n >> .env
          echo ORDER_PORT=1998\n >> .env
          echo ORDER_PROFILE=default\n >> .env
          echo INVENTORY_CLIENT_ADDRESS=static://inventory:9090\n >> .env
          echo INVENTORY_PORT=1997\n >> .env
          echo INVENTORY_PROFILE=e2e\n >> .env
          echo INVENTORY_GRPC_SERVER_PORT=9090\n >> .env

      - name: compose up
        run: docker compose -f compose-gateway.yml up -d

      - name: inventory tests
        run: |
          cd inventory/
          mvn clean test

      - name: order tests
        run: |
          cd order/
          mvn clean test

      - name: e2e test
        run: |
          docker ps
          cd e2e/
          javac main.java
          java main.java 8080

      - name: compose down
        run: docker compose down -v